name: sudoku
channels:
  - defaults
  - conda-forge
dependencies:
  - asgiref=3.4.1
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - django=3.2.5
  - krb5=1.19.2
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libffi=3.3
  - libpq=12.9
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.4
  - psycopg2=2.8.6
  - python=3.8.13
  - pytz=2021.3
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - sqlparse=0.4.1
  - tk=8.6.11
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
